[build]
builder = "nixpacks"
buildCommand = "pip install -r backend/requirements.txt && cd frontend && npm install && npm run build"

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
PYTHON_VERSION = "3.10"
VITE_API_URL = "https://$RAILWAY_PUBLIC_DOMAIN/api" 