[build]
builder = "nixpacks"
buildCommand = "pip install -r backend/requirements.txt"

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
PYTHON_VERSION = "3.10"
DATABASE_URL = "postgresql://postgres:postgres@db:5432/ecfr"

[[services]]
name = "frontend"
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build"
startCommand = "cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[services.deploy.env]
VITE_API_URL = "https://$RAILWAY_PUBLIC_DOMAIN/api" 